In [1]:
import os
import torch
import torchvision.transforms as transforms
from torchvision.datasets import ImageFolder
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim
from torchvision import models


In [104]:
import os
from PIL import Image

# Görüntü dosyalarının bulunduğu dizin
image_dir ='E:/datasets/datasets_gemstone/test/' # Kendi dizin yolunuzu buraya ekleyin

# Desteklenen görüntü formatları
supported_formats = ('.jpg', '.jpeg', '.png')

# Klasörü tarayıp görüntüleri kontrol et
for class_dir in os.listdir(image_dir):
    class_path = os.path.join(image_dir, class_dir)
    
    # Sınıf klasörü olup olmadığını kontrol et
    if os.path.isdir(class_path):
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            
            # Dosya formatını kontrol et
            if img_name.lower().endswith(supported_formats):
                try:
                    # Görüntüyü aç
                    with Image.open(img_path) as img:
                        # Görüntü boyutlarını kontrol et
                        if img.mode != 'RGB':
                            print(f"Deleting {img_path} (not RGB)")
                            os.remove(img_path)  # 3 kanallı olmayan görüntüyü sil
                        else:
                            print(f"Keeping {img_path}")  # 3 kanallı görüntüyü tut
                except Exception as e:
                    print(f"Error processing {img_path}: {e}")
                    # Hata durumunda dosyayı silebilirsiniz (isteğe bağlı)
                    # os.remove(img_path)


Keeping E:/datasets/datasets_gemstone/test/Alexandrite\alexandrite_18.jpg
Keeping E:/datasets/datasets_gemstone/test/Alexandrite\alexandrite_28.jpg
Keeping E:/datasets/datasets_gemstone/test/Alexandrite\alexandrite_3.jpg
Keeping E:/datasets/datasets_gemstone/test/Alexandrite\alexandrite_6.jpg
Keeping E:/datasets/datasets_gemstone/test/Almandine\almandine_18.jpg
Keeping E:/datasets/datasets_gemstone/test/Almandine\almandine_28.jpg
Keeping E:/datasets/datasets_gemstone/test/Almandine\almandine_3.jpg
Keeping E:/datasets/datasets_gemstone/test/Almandine\almandine_9.jpg
Keeping E:/datasets/datasets_gemstone/test/Amazonite\amazonite_18.jpg
Keeping E:/datasets/datasets_gemstone/test/Amazonite\amazonite_28.jpg
Keeping E:/datasets/datasets_gemstone/test/Amazonite\amazonite_3.jpg
Keeping E:/datasets/datasets_gemstone/test/Amazonite\amazonite_8.jpg
Keeping E:/datasets/datasets_gemstone/test/Amber\amber_18.jpg
Keeping E:/datasets/datasets_gemstone/test/Amber\amber_28.jpg
Keeping E:/datasets/datase

In [105]:
import os
import pandas as pd
from PIL import Image

# Dataset yolunu belirtin
dataset_dir = 'E:/datasets/datasets_gemstone/train/'

train_data = []
train_labels = []

# Eğitim verilerini yükleme
for class_name in os.listdir(dataset_dir):
    class_dir = os.path.join(dataset_dir, class_name)
    if os.path.isdir(class_dir):  # Sadece dizinleri kontrol et
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            # Görüntüyü yükle
            with Image.open(img_path) as image:
                train_data.append(image.copy())  # Görüntüyü kopyala
                train_labels.append(class_name)  # Sınıf adını etiket olarak ekle

# DataFrame oluşturma
df = pd.DataFrame({
    'image': train_data,
    'label': train_labels
})

# DataFrame'i görüntüleme
print(df.head())


                                               image        label
0  <PIL.Image.Image image mode=RGB size=225x225 a...  Alexandrite
1  <PIL.Image.Image image mode=RGB size=251x228 a...  Alexandrite
2  <PIL.Image.Image image mode=RGB size=347x347 a...  Alexandrite
3  <PIL.Image.Image image mode=RGB size=218x231 a...  Alexandrite
4  <PIL.Image.Image image mode=RGB size=395x395 a...  Alexandrite


In [106]:
df_train=df

In [107]:
import os
import pandas as pd
from PIL import Image

# Dataset yolunu belirtin
dataset_dir = 'E:/datasets/datasets_gemstone/test/'

test_data = []
test_labels = []

# Eğitim verilerini yükleme
for class_name in os.listdir(dataset_dir):
    class_dir = os.path.join(dataset_dir, class_name)
    if os.path.isdir(class_dir):  # Sadece dizinleri kontrol et
        for img_name in os.listdir(class_dir):
            img_path = os.path.join(class_dir, img_name)
            # Görüntüyü yükle
            with Image.open(img_path) as image:
                test_data.append(image.copy())  # Görüntüyü kopyala
                test_labels.append(class_name)  # Sınıf adını etiket olarak ekle

# DataFrame oluşturma
df_test = pd.DataFrame({
    'image': test_data,
    'label': test_labels
})

# DataFrame'i görüntüleme
print(df.head())


                                               image        label
0  <PIL.Image.Image image mode=RGB size=225x225 a...  Alexandrite
1  <PIL.Image.Image image mode=RGB size=251x228 a...  Alexandrite
2  <PIL.Image.Image image mode=RGB size=347x347 a...  Alexandrite
3  <PIL.Image.Image image mode=RGB size=218x231 a...  Alexandrite
4  <PIL.Image.Image image mode=RGB size=395x395 a...  Alexandrite


In [108]:
combined_df = pd.concat([df_train,df_test], ignore_index=True)

print(combined_df)

                                                  image        label
0     <PIL.Image.Image image mode=RGB size=225x225 a...  Alexandrite
1     <PIL.Image.Image image mode=RGB size=251x228 a...  Alexandrite
2     <PIL.Image.Image image mode=RGB size=347x347 a...  Alexandrite
3     <PIL.Image.Image image mode=RGB size=218x231 a...  Alexandrite
4     <PIL.Image.Image image mode=RGB size=395x395 a...  Alexandrite
...                                                 ...          ...
3211  <PIL.Image.Image image mode=RGB size=314x410 a...       Zircon
3212  <PIL.Image.Image image mode=RGB size=225x225 a...      Zoisite
3213  <PIL.Image.Image image mode=RGB size=420x420 a...      Zoisite
3214  <PIL.Image.Image image mode=RGB size=225x225 a...      Zoisite
3215  <PIL.Image.Image image mode=RGB size=454x454 a...      Zoisite

[3216 rows x 2 columns]


In [109]:
combined_df

image        label
0     <PIL.Image.Image image mode=RGB size=225x225 a...  Alexandrite
1     <PIL.Image.Image image mode=RGB size=251x228 a...  Alexandrite
2     <PIL.Image.Image image mode=RGB size=347x347 a...  Alexandrite
3     <PIL.Image.Image image mode=RGB size=218x231 a...  Alexandrite
4     <PIL.Image.Image image mode=RGB size=395x395 a...  Alexandrite
...                                                 ...          ...
3211  <PIL.Image.Image image mode=RGB size=314x410 a...       Zircon
3212  <PIL.Image.Image image mode=RGB size=225x225 a...      Zoisite
3213  <PIL.Image.Image image mode=RGB size=420x420 a...      Zoisite
3214  <PIL.Image.Image image mode=RGB size=225x225 a...      Zoisite
3215  <PIL.Image.Image image mode=RGB size=454x454 a...      Zoisite

[3216 rows x 2 columns]

In [110]:
from torch.utils.data import Dataset ,DataLoader
from torchvision import transforms
from sklearn.preprocessing import LabelEncoder

In [111]:
label_encoder=LabelEncoder()

In [112]:
combined_df["label"]=label_encoder.fit_transform(combined_df["label"])

In [113]:
combined_df

image  label
0     <PIL.Image.Image image mode=RGB size=225x225 a...      0
1     <PIL.Image.Image image mode=RGB size=251x228 a...      0
2     <PIL.Image.Image image mode=RGB size=347x347 a...      0
3     <PIL.Image.Image image mode=RGB size=218x231 a...      0
4     <PIL.Image.Image image mode=RGB size=395x395 a...      0
...                                                 ...    ...
3211  <PIL.Image.Image image mode=RGB size=314x410 a...     85
3212  <PIL.Image.Image image mode=RGB size=225x225 a...     86
3213  <PIL.Image.Image image mode=RGB size=420x420 a...     86
3214  <PIL.Image.Image image mode=RGB size=225x225 a...     86
3215  <PIL.Image.Image image mode=RGB size=454x454 a...     86

[3216 rows x 2 columns]

In [114]:
num_classes=combined_df['label'].nunique()

In [115]:
num_classes

87

In [116]:
print(label_encoder.classes_.shape)

(87,)


In [117]:
import torch 
from torch.utils.data import Dataset
from PIL import Image

In [118]:
class CustomDataset(Dataset):
    def __init__ (self,dataframe,transform=None):
        self.data=dataframe
        self.transform=transform
    def __len__(self):

        return len(self.data)

        
    def __getitem__(self,index):

        label=self.data.iloc[index]["label"]

        image=self.data.iloc[index]["image"]

        if self.transform:
            image=self.transform(image)


        return image, label






In [119]:
from torchvision import transforms

In [120]:
dataframe=combined_df

In [121]:
transform = transforms.Compose([
    
    transforms.Resize((224, 224)),  # RESNET İÇİN
    transforms.ToTensor(),  # Görüntüyü tensöre çeviriyoruz
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # Normalizasyon
                         std=[0.229, 0.224, 0.225])
])

In [122]:
dataset=CustomDataset(dataframe=dataframe,transform=transform)

In [123]:
image,label=dataset[0]

In [124]:
image.shape

torch.Size([3, 224, 224])

In [125]:
dataset

In [126]:
from sklearn.model_selection import train_test_split

In [127]:
labels = dataset.data['label'].values[:len(dataset)]  

indices = list(range(len(dataset)))
train_indices, test_indices = train_test_split(indices, test_size=0.2, stratify=labels)

train_dataset = torch.utils.data.Subset(dataset, train_indices)
test_dataset = torch.utils.data.Subset(dataset, test_indices)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [128]:
for x,y in train_loader: 
    print(y)

tensor([78, 83, 60, 74, 62, 49,  4, 85, 73, 68, 33, 65, 76, 55, 60, 78,  0, 18,
        46,  0,  0, 39, 12, 57, 39,  3, 57, 55, 10, 38, 68, 75, 69, 55, 34, 58,
        21, 60, 27, 60, 52,  6, 79, 10, 10, 19, 28, 60, 57, 68, 40, 83, 10, 71,
        69, 23, 73, 12, 57, 76, 23, 26,  4, 25], dtype=torch.int32)
tensor([80, 54, 54, 48, 43, 36, 55,  3, 39, 44,  9, 79, 33, 74, 81, 29, 24,  8,
         5, 73, 48, 61, 72, 43, 38, 35, 82, 42, 75, 67, 25, 80, 24, 19, 56, 53,
        45, 19, 32, 36, 58, 76, 81, 14, 28, 52, 66, 19, 17, 77, 69, 28, 78, 17,
        19, 15,  3, 37, 72, 44, 66, 76, 52, 22], dtype=torch.int32)
tensor([86,  2, 79, 19, 24, 14,  4, 12,  2,  8, 21, 19, 50, 79, 84, 24, 24, 72,
        29,  2, 53, 55, 63, 14, 81, 52, 15, 79, 53, 11, 40, 83, 30, 46, 30, 13,
        11, 14,  7, 81, 69, 13, 27, 74, 10, 43, 14, 42,  9, 64, 38, 26, 51, 66,
        34, 77, 67,  5, 79,  7, 26, 60,  6, 13], dtype=torch.int32)
tensor([18, 84, 41, 45, 36, 45, 63, 82, 37, 31, 31, 14, 24, 71,  7, 15, 83, 

In [129]:
print(f"Train dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")


Train dataset size: 2572
Test dataset size: 644


In [130]:
if torch.cuda.is_available():
    device=torch.device("cuda")

In [131]:
device
import torch.nn as nn

In [132]:
import torchvision.models as models

model= models.resnet18(pretrained=True)

num_classes = 87 
model.fc = nn.Linear(model.fc.in_features, num_classes)  # SON KATMANI SINIF SAYISINA GÖRE DEĞİŞTİRİYORUZ


c:\Users\ninja\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\ninja\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [133]:
for x,y in train_loader:
    print(x.shape)

torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size([64, 3, 224, 224])
torch.Size

In [134]:
model


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [135]:
model.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [136]:
from torchsummary import summary 

In [137]:
summary(model,input_size=(3,224,224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 112, 112]           9,408
       BatchNorm2d-2         [-1, 64, 112, 112]             128
              ReLU-3         [-1, 64, 112, 112]               0
         MaxPool2d-4           [-1, 64, 56, 56]               0
            Conv2d-5           [-1, 64, 56, 56]          36,864
       BatchNorm2d-6           [-1, 64, 56, 56]             128
              ReLU-7           [-1, 64, 56, 56]               0
            Conv2d-8           [-1, 64, 56, 56]          36,864
       BatchNorm2d-9           [-1, 64, 56, 56]             128
             ReLU-10           [-1, 64, 56, 56]               0
       BasicBlock-11           [-1, 64, 56, 56]               0
           Conv2d-12           [-1, 64, 56, 56]          36,864
      BatchNorm2d-13           [-1, 64, 56, 56]             128
             ReLU-14           [-1, 64,

In [138]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [147]:
num_epochs = 1

for epoch in range(num_epochs):
    model.train()  
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        # Forward pass
        outputs = model(images)
        labels=labels.long()
        #print(outputs.dtype)
        #print(labels.dtype)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}")


Epoch [1/1], Loss: 0.0245


In [148]:
model.eval()   
correct = 0
total = 0

with torch.no_grad():   
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total:.2f}%')

Accuracy: 74.69%


In [149]:
torch.save(model.state_dict(), 'resnet18_finetuned_geam.pth')


In [150]:
torch.save(model.state_dict(), 'model_checkpoint_rest_net_ge.pth')


In [ ]:
optimizer = optim.Adam(model.parameters(), lr=0.001)
model.load_state_dict(torch.load('model_checkpoint.pth'))
