In [1]:
import torch 
import torchvision 
import numpy as np
import os 
import pandas as pd 
from PIL import Image
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
path="E:\\datasets\\yoga pose estimation\\"

In [3]:
test_df=pd.read_pickle(path+"datasettest_df_yoga.pkl")

In [4]:
test_df

Label  \
0          eka pada rajakapotasana   
1                         savasana   
2          ardha pincha mayurasana   
3            adho mukha vriksasana   
4                     bhairavasana   
...                            ...   
1121                    garudasana   
1122               viparita karani   
1123              urdhva hastasana   
1124  utthita ashwa sanchalanasana   
1125                      malasana   

                                                  Image  
0     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
2     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
3     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
...                                                 ...  
1121  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1122  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1123  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1124  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1125  <PIL.PngImagePlugin.PngImageFile image mode=RG...  

[1126 rows x 2 columns]

In [5]:
train_df=pd.read_pickle(path+"datasettrain_yoga.pkl")

In [6]:
from torch.utils.data import Dataset ,DataLoader
from torchvision import transforms
from sklearn.preprocessing import LabelEncoder

In [7]:
train_df

Label  \
0      eka pada rajakapotasana   
1             bharadvajasana i   
2                bhujapidasana   
3       urdhva mukha svanasana   
4                   anantasana   
...                        ...   
4496  setu bandha sarvangasana   
4497           viparita karani   
4498        paripurna navasana   
4499  setu bandha sarvangasana   
4500      chaturanga dandasana   

                                                  Image  
0     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
2     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
3     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
...                                                 ...  
4496  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4497  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4498  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4499  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4500  <PIL.PngImagePlugin.PngImageFile image mode=RG...  

[4501 rows x 2 columns]

In [8]:
combined_df = pd.concat([train_df, test_df], ignore_index=True)

print(combined_df)

                             Label  \
0          eka pada rajakapotasana   
1                 bharadvajasana i   
2                    bhujapidasana   
3           urdhva mukha svanasana   
4                       anantasana   
...                            ...   
5622                    garudasana   
5623               viparita karani   
5624              urdhva hastasana   
5625  utthita ashwa sanchalanasana   
5626                      malasana   

                                                  Image  
0     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
2     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
3     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
...                                                 ...  
5622  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5623  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5624  <PIL.PngImagePl

In [9]:
combined_df

Label  \
0          eka pada rajakapotasana   
1                 bharadvajasana i   
2                    bhujapidasana   
3           urdhva mukha svanasana   
4                       anantasana   
...                            ...   
5622                    garudasana   
5623               viparita karani   
5624              urdhva hastasana   
5625  utthita ashwa sanchalanasana   
5626                      malasana   

                                                  Image  
0     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
1     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
2     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
3     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
4     <PIL.PngImagePlugin.PngImageFile image mode=RG...  
...                                                 ...  
5622  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5623  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5624  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5625  <PIL.PngImagePlugin.PngImageFile image mode=RG...  
5626  <PIL.PngImagePlugin.PngImageFile image mode=RG...  

[5627 rows x 2 columns]

In [33]:
combined_df.

TypeError: Cannot index by location index with a non-integer key

In [10]:
label_encoder=LabelEncoder()

In [11]:
combined_df["Label"]=label_encoder.fit_transform(combined_df["Label"])

In [12]:
combined_df

Label                                              Image
0        31  <PIL.PngImagePlugin.PngImageFile image mode=RG...
1        17  <PIL.PngImagePlugin.PngImageFile image mode=RG...
2        20  <PIL.PngImagePlugin.PngImageFile image mode=RG...
3        87  <PIL.PngImagePlugin.PngImageFile image mode=RG...
4         4  <PIL.PngImagePlugin.PngImageFile image mode=RG...
...     ...                                                ...
5622     35  <PIL.PngImagePlugin.PngImageFile image mode=RG...
5623     99  <PIL.PngImagePlugin.PngImageFile image mode=RG...
5624     86  <PIL.PngImagePlugin.PngImageFile image mode=RG...
5625     93  <PIL.PngImagePlugin.PngImageFile image mode=RG...
5626     46  <PIL.PngImagePlugin.PngImageFile image mode=RG...

[5627 rows x 2 columns]

In [34]:
num_classes=combined_df['Label'].nunique()

In [35]:
num_classes

107

In [13]:
print(label_encoder.classes_.shape)

(107,)


In [14]:
dataframe=combined_df

In [15]:
import torch 
from torch.utils.data import Dataset
from PIL import Image

In [16]:
class CustomDataset(Dataset):
    def __init__ (self,dataframe,transform=None):
        self.data=dataframe
        self.transform=transform
    def __len__(self):

        return len(self.data)

        
    def __getitem__(self,index):

        label=self.data.iloc[index]["Label"]

        image=self.data.iloc[index]["Image"]

        if self.transform:
            image=self.transform(image)


        return image, label






In [17]:
from torchvision import transforms

In [18]:
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # RESNET İÇİN
    transforms.ToTensor(),  # Görüntüyü tensöre çeviriyoruz
    transforms.Normalize(mean=[0.485, 0.456, 0.406],  # Normalizasyon
                         std=[0.229, 0.224, 0.225])
])

In [19]:
dataset=CustomDataset(dataframe=dataframe,transform=transform)

In [20]:
image,label=dataset[0]

In [21]:
 label.shape

()

In [22]:
image.shape

torch.Size([3, 224, 224])

In [23]:
dataset

In [24]:
labels = dataset.data['Label'].values[:len(dataset)]  

indices = list(range(len(dataset)))
train_indices, test_indices = train_test_split(indices, test_size=0.2, stratify=labels)

train_dataset = torch.utils.data.Subset(dataset, train_indices)
test_dataset = torch.utils.data.Subset(dataset, test_indices)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [25]:
for x,y in train_loader: 
    print(y)

tensor([ 67,  56,  84,  97,  46,  98,  89,  70,  31,  47,  14,  64,   6,  39,
         73,  43, 100,  95,  46,  60,  77,  72,   9,  75,  18,  94,  86,  14,
         97,  56,  37,  73], dtype=torch.int32)
tensor([ 70,   7,  98,  74,  36,  43,  11,  87,  71, 102,  46, 103,  81,  74,
         41,  95,  51,  34,  99,  89,  29,  35,  14,  22,  20,  18,  52, 100,
         69,  87,  64,  38], dtype=torch.int32)
tensor([ 21,  67,  62,  76,  73,  76,  70, 102,  66,  41,  63,  86,  56,  23,
        102,   9,  89,  99,  73,  21,  56,  36,  61,  99,  86,  99,  98,  40,
         34,  75,  27,  89], dtype=torch.int32)
tensor([ 76, 105,  18,   1,  38,  59,  65,  53,  35,  42, 105,  66,  73,   4,
         12,  24,  36,  51,  21,  37,  10,  88,  24,  52,  92,  65,  14,  55,
         55,  22,  83,  89], dtype=torch.int32)
tensor([ 75,  17,  41,  73,  60,  34,  76,  14,  29,  52,  68,  73,  34,  22,
         66,  82,  64,  71,  92,  36,  10,  12,  68, 100,  58,  71,  82,  85,
         29,  81,  20,  24],

KeyboardInterrupt: 

In [27]:
print(f"Train dataset size: {len(train_dataset)}")
print(f"Test dataset size: {len(test_dataset)}")


Train dataset size: 4501
Test dataset size: 1126


In [29]:
if torch.cuda.is_available():
    device=torch.device("cuda")

In [30]:
device
import torch.nn as nn

# RESNET 

In [36]:
import torchvision.models as models

model= models.resnet18(pretrained=True)

num_classes = 107  
model.fc = nn.Linear(model.fc.in_features, num_classes)  # SON KATMANI SINIF SAYISINA GÖRE DEĞİŞTİRİYORUZ


c:\Users\ninja\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\ninja\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [38]:
model


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [39]:
model.to(device)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [41]:
from torchsummary import summary 

In [42]:
summary(model,input_size=(3,224,224))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Conv2d-1         [-1, 64, 112, 112]           9,408
       BatchNorm2d-2         [-1, 64, 112, 112]             128
              ReLU-3         [-1, 64, 112, 112]               0
         MaxPool2d-4           [-1, 64, 56, 56]               0
            Conv2d-5           [-1, 64, 56, 56]          36,864
       BatchNorm2d-6           [-1, 64, 56, 56]             128
              ReLU-7           [-1, 64, 56, 56]               0
            Conv2d-8           [-1, 64, 56, 56]          36,864
       BatchNorm2d-9           [-1, 64, 56, 56]             128
             ReLU-10           [-1, 64, 56, 56]               0
       BasicBlock-11           [-1, 64, 56, 56]               0
           Conv2d-12           [-1, 64, 56, 56]          36,864
      BatchNorm2d-13           [-1, 64, 56, 56]             128
             ReLU-14           [-1, 64,

In [43]:
model.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [45]:
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)


In [50]:
num_epochs = 10

for epoch in range(num_epochs):
    model.train()  
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
        # Forward pass
        outputs = model(images)
        labels=labels.long()
        #print(outputs.dtype)
        #print(labels.dtype)
        loss = criterion(outputs, labels)

        # Backward pass and optimization
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}")


Epoch [1/10], Loss: 2.1229
Epoch [2/10], Loss: 1.1548
Epoch [3/10], Loss: 0.7145
Epoch [4/10], Loss: 0.4169
Epoch [5/10], Loss: 0.2754
Epoch [6/10], Loss: 0.2014
Epoch [7/10], Loss: 0.1523
Epoch [8/10], Loss: 0.1177
Epoch [9/10], Loss: 0.1001
Epoch [10/10], Loss: 0.1175


In [51]:
model.eval()   
correct = 0
total = 0

with torch.no_grad():   
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total:.2f}%')

Accuracy: 65.10%


In [52]:
torch.save(model.state_dict(), 'resnet18_finetuned_yoga.pth')


In [53]:
torch.save(model.state_dict(), 'model_checkpoint.pth')


In [56]:

optimizer = optim.Adam(model.parameters(), lr=0.001)
model.load_state_dict(torch.load('model_checkpoint.pth'))

start_epoch = 20  

num_epochs = 24  

for epoch in range(start_epoch, start_epoch + num_epochs):
    model.train()  
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        optimizer.zero_grad()
         
        outputs = model(images)
        labels = labels.long()

        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()
    
    print(f"Epoch [{epoch+1}/{start_epoch + num_epochs}], Loss: {running_loss/len(train_loader):.4f}")

 
torch.save(model.state_dict(), 'model_checkpoint.pth')


C:\Users\ninja\AppData\Local\Temp\ipykernel_32916\603424615.py:8: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load('model_checkpoint.pth'))


Epoch [21/44], Loss: 0.1516
Epoch [22/44], Loss: 0.1140
Epoch [23/44], Loss: 0.1134
Epoch [24/44], Loss: 0.1469
Epoch [25/44], Loss: 0.1262
Epoch [26/44], Loss: 0.0920
Epoch [27/44], Loss: 0.0844
Epoch [28/44], Loss: 0.0802
Epoch [29/44], Loss: 0.0899
Epoch [30/44], Loss: 0.0772
Epoch [31/44], Loss: 0.0965
Epoch [32/44], Loss: 0.1136
Epoch [33/44], Loss: 0.0929
Epoch [34/44], Loss: 0.0561
Epoch [35/44], Loss: 0.0395
Epoch [36/44], Loss: 0.0422
Epoch [37/44], Loss: 0.0350
Epoch [38/44], Loss: 0.0344
Epoch [39/44], Loss: 0.0306
Epoch [40/44], Loss: 0.0319
Epoch [41/44], Loss: 0.0333
Epoch [42/44], Loss: 0.0334
Epoch [43/44], Loss: 0.0303
Epoch [44/44], Loss: 0.0309


In [57]:
model.eval()   
correct = 0
total = 0

with torch.no_grad():   
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print(f'Accuracy: {100 * correct / total:.2f}%')

Accuracy: 73.18%
